### ISSUE TITLE
CC is the name of a compiler...

### ISSUE THREAD

**Issue by Qix-** [lovell/cc#1]
```json
{
  "bin": { "cc": "..." }
}
```

You realize that `cc` is the standard link name for the system's C compiler, right? You're going to cause a ton of conflicts when installing this package.

**Comment by lovell** [comment]
Hello, if you didn't see it there's logic to spawn the underlying `cc` directly when invoked with arguments:

https://github.com/lovell/cc/blob/07c15eff755f9f4513b05d371c240c293986f672/bin/cc.js#L10-L13

Was this question about a real problem you've experienced? If so, are you able to provide steps to reproduce?

**Comment by Qix-** [comment]
No, but this paradigm of masking the real CC is bad practice. You'll break a ton of tooling.

**Comment by lovell** [comment]
I'm not aware of any tooling that is broken by this approach.

I do agree that the naming could cause confusion so let's go with something like `cclint` for the `.bin` entry instead, perhaps initially as an additional entry, then we can remove `cc` in a v2 major increment.

**Comment by lovell** [comment]
The `bin` entry is renamed `cpplint` in v2 to avoid confusion - thanks for reporting this.
